// <auto-generated />
using LibraryMVC.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace LibraryMVC.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20180506202548_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryMVC.Domain.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Name");

                    b.Property<int>("NumberAvailableBooks");

                    b.HasKey("ID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("LibraryMVC.Domain.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BorrowedBooksID");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("NickName");

                    b.HasKey("ID");

                    b.HasIndex("BorrowedBooksID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LibraryMVC.Domain.Models.User", b =>
                {
                    b.HasOne("LibraryMVC.Domain.Models.Book", "BorrowedBooks")
                        .WithMany()
                        .HasForeignKey("BorrowedBooksID");
                });
#pragma warning restore 612, 618
        }
    }
}
